#!/usr/bin/env python3

import json
import locale
import sys
import reports
import emails
import os

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales": 0}
  sale_year = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item
    if item["car"]["car_year"] not in sale_year.keys():
      sale_year[item["car"]["car_year"]] = item["total_sales"]
    else:
      sale_year[item["car"]["car_year"]] += item["total_sales"]
  max_sale = max(sale_year.values())
  for k, v in sale_year.items():
    if v == max_sale:
      year = k

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(
      format_car(max_sales["car"]), max_sales["total_sales"]),
    "The most popular year was {} with {} sales".format(
      year, max_sale),
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  table_data = cars_dict_to_table(data)
  para = summary[0] + "\n" + summary[1] + "\n" + summary[2]
  para_pdf = summary[0] + "<br/>" + summary[1] + "<br/>" + summary[2]
  reports.generate("/tmp/cars.pdf", "Sales Summary for last month", para_pdf, table_data)
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = para_pdf

  message = emails.generate(sender, receiver, subject, "PFA the summary for last month", "/tmp/cars.pdf")
  emails.send(message)
  print(para)

if __name__ == "__main__":
  main(sys.argv)
